version: '3'

services:
  adonis-api:
    build:
      context: .
      dockerfile: docker/adonis-prod.dockerfile
    container_name: ${APP_NAME}-api
    hostname: ${APP_NAME}
    command: npm run pm2-docker
    volumes:
      - ./.env:/var/app/.env
      - ./logs/:/var/app/logs/
    ports:
      - '${PORT}:${PORT}'
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./data-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Bangkok
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

    ports:
      - '${MYSQL_PORT_FOR_DOCKER}:3306'

  redis:
    image: redis:6.2
    container_name: ${APP_NAME}-redis
    ports:
      - '${REDIS_PORT_FOR_DOCKER}:6379'
